### ISSUE TITLE
Wrong image set

### ISSUE THREAD

**Issue by beatadetkova** [e1ven/Robohash#38]
Using `https://robohash.org/kitty?set=set4` I am getting a kitty picture like it should:

![](https://robohash.org/kitty?set=set4)

But if I provide `https://robohash.org/kittytit?set=set4` I am getting a robot:

![](https://robohash.org/kittytit?set=set4)

And if I try something close to it like `https://robohash.org/kittyt?set=set4` then I'm getting back a kitty again:

![](https://robohash.org/kittyt?set=set4)

Not sure what went wrong there... :yum:

**Comment by pajasry** [comment]
I have the same problem. I realize, that its depends on the extension in some cases. For example [/sry?set=set4](https://robohash.org/sry?set=set4) return kitty, but [/sry.png?set=set4](https://robohash.org/sry.png?set=set4) gives me a robot from set 1. It's weird because due to source code, it should ignore extensions by default. Am I missing something here?

**Comment by Sebring** [comment]
@pajasry I'm getting cats in both of your links. Also, I only see cats in @beatadetkova original post. This is maybe fixed?

**Comment by wachunga** [comment]
It's happening again: I do not get cats for this request
https://robohash.org/4.png?set=set4

**Comment by n8-dev** [comment]
Confirm above images are all robots right now.

**Comment by j-dobr** [comment]
And including size parameter (e.g. https://robohash.org/4.png?set=set4&size=200x200) returns 500 with or without set alike.

**Comment by e1ven** [comment]
@j-dobr - I think this should be resolved. :crossed_fingers:

**Comment by e1ven** [comment]
@wachunga

I scaled up the number of workers and purged the cache with cloudflare, hopefully that should fix for you.
