### ISSUE TITLE
Incrementing Bgset stops at 2?

### ISSUE THREAD

**Issue by kenchambers** [e1ven/Robohash#49]
I tried to go past bgset2 and i wasn't able to get any images behind my robots

Link not working:  `https://robohash.org/3f6e64bb.png?bgset=bg3`

BTW absolutely love the library, using it my app :)

**Comment by e1ven** [comment]
There are only two sets of backgrounds :) 
https://github.com/e1ven/Robohash/tree/master/robohash/backgrounds

**Comment by e1ven** [comment]
Sorry - Maybe I'm missing context - Was there something else you expected to happen?

**Comment by pierroo** [comment]
Hey @e1ven , I'm a bit late to the party but:
to be honest I was also expecting bgSet to be an incremented counter, where each number links to a specific background.
it doesn't have to be random like the actual hash "name", ideally if we edit the url with a specific param for bg, just like for the size, we expect a specific bg output.
So instead of having all bg into 1 and 2 only with 10 variations each, it could just be bg1...20

would it be possible?
